name: Docker Continuous Delivery

# only run when a new release is created
on:
  release: 
    types: [created]

env:
  DOCKER_REGISTRY_URL: ghcr.io
  DOCKER_IMAGE_NAME: ${{ github.repository }}

# Jobs triggered on workflow run.
jobs:
  build-and-release-docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Install QEMU to emulate different architecture (required to use buildx for ARM)
      - name: Set up QEMU
        if: success()
        uses: docker/setup-qemu-action@v3

      # Install docker buildx to build image for multiple architectures
      - name: Docker Setup Buildx
        if: success()
        uses: docker/setup-buildx-action@v3

      # build and publish image for multiple architectures
      - name: Build and publish
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref.name }},${{ env.DOCKER_IMAGE_NAME }}:latest
